disabled_rules:
  - line_length
  - trailing_newline
  - trailing_whitespace
  - identifier_name
  - type_name
  - todo
  - nesting

excluded:
  - Docs
  - Frameworks
  - Pods

identifier_name:
  min_length: 1
  max_length: 40

function_body_length: 350
file_length: 800
type_body_length: 800
